[package]
name = "beginner"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true, features = ["webgl"] }
env_logger.workspace = true
log.workspace = true
parking_lot.workspace = true
pollster.workspace = true
winit.workspace = true
utils.workspace = true
