[package]
name = "beginner"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger.workspace = true
log.workspace = true
parking_lot.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true
utils.workspace = true
