[package]
name = "beginner-02"
version = "0.1.0"
edition = "2024"

[dependencies]
app-surface.workspace = true
wgpu.workspace = true
winit.workspace = true
utils.workspace = true
bytemuck.workspace = true
image.workspace = true

[features]
webgl = ["wgpu/webgl", "app-surface/webgl"]
